

NodeKind_ProK             = "ProK"
NodeKind_PheadK           = "PheadK"
NodeKind_TypeK            = "TypeK"
NodeKind_VarK             = "VarK"
NodeKind_ProcDecK         = "ProcDecK"
NodeKind_StmLK            = "StmLK"
NodeKind_DecK             = "DecK"
NodeKind_StmtK            = "StmtK"
NodeKind_ExpK             = "ExpK"
NodeKind_DefaultNodeKind  = ""

Kind_ArrayK       = "ArrayK"
Kind_CharK        = "CharK"
Kind_IntegerK     = "IntegerK"
Kind_RecordK      = "RecordK"
Kind_IdK          = "IdK"
Kind_IfK          = "IfK"
Kind_WhileK       = "WhileK"
Kind_AssignK      = "AssignK"
Kind_ReadK        = "ReadK"
Kind_WriteK       = "WriteK"
Kind_CallK        = "CallK"
Kind_ReturnK      = "ReturnK"
Kind_OpK          = "OpK"
Kind_ConstK       = "ConstK"
Kind_DefaultKind  = ""

ProcParamType_ValParamType      = "valparam"
ProcParamType_VarParamType      = "varparam"
ProcParamType_DefaultParamType  = ""

ExpVarKind_IdV                = "IdV"
ExpVarKind_ArrayMembV         = "ArrayMemebV"
ExpVarKind_ParamMembV         = "ParamMembV"
ExpVarKind_FieldMembV         = "FieldMembV"
ExpVarKind_DefaultExpVarKind  = ""

ExpType_ExpInteger      = "Integer"
ExpType_ExpBoolean      = "Boolean"
ExpType_DefaultExpType  = ""

ChildType_Char     = "CharK"
ChildType_Integer  = "IntegerK"